// src/lib/components/notifications/UnknownNotification.svelte
<script lang="ts">
  import Icon from "svelte-fa";
  import { faInfoCircle } from "@fortawesome/free-solid-svg-icons";
  import type { GetNotificationsQuery } from "@anilist/graphql";
  import NotificationContainer from "./NotificationContainer.svelte";

  export let notification: GetNotificationsQuery["Page"]["notifications"][0];
  export let unread = false;
</script>

<NotificationContainer {unread} createdAt={notification.createdAt}>
  <Icon icon={faInfoCircle} class="flex-none w-12 text-3xl mr-4 aspect-square text-yellow" />
  <span class="line-clamp-3 mr-6 flex-1">
    {notification.type}
    is an unknown notification type. Please 
    <a href="https://github.com/TehNut/AniMouto" target="_blank" class="text-accent">report this</a>
    so it can be supported!
  </span>
</NotificationContainer>

// src/popup/components/notifications/type/UnknownNotification.vue
<template>
  <span>
    <i class="material-icons avatar notification-icon no-select">notification_important</i>
    <a href="https://github.com/TehNut/AniMouto/issues" class="notification-body" target="_blank" :title="JSON.stringify(notification)">
      <div>
        This is an <span style="color:rgb(var(--color-red))">unknown</span> notification type. Please report this so it can have support added.
      </div>
    </a>
  </span>
</template>

<script>
  export default {
    name: "UnknownNotification",
    props: [
      "notification"
    ]
  }
</script>

<style scoped>
  .notification-icon {
    font-size: 40px;
    margin-top: 6px;
  }
</style>
